import { Injectable } from "@angular/core";


@Injectable({
    providedIn: 'root'
})
export class AppConstants {

    // public countryList:any=[
    //     { "country_id": "AF", "name": "Afghanistan" },
    //     { "country_id": "AL", "name": "Albania" },
    //     { "country_id": "DZ", "name": "Algeria" },
    //     { "country_id": "AS", "name": "American Samoa" },
    //     { "country_id": "AD", "name": "Andorra" },
    //     { "country_id": "AO", "name": "Angola" },
    //     { "country_id": "AI", "name": "Anguilla" },
    //     { "country_id": "AQ", "name": "Antarctica" },
    //     { "country_id": "AG", "name": "Antigua and Barbuda" },
    //     { "country_id": "AR", "name": "Argentina" },
    //     { "country_id": "AM", "name": "Armenia" },
    //     { "country_id": "AW", "name": "Aruba" },
    //     { "country_id": "AU", "name": "Australia" },
    //     { "country_id": "AT", "name": "Austria" },
    //     { "country_id": "AZ", "name": "Azerbaijan" },
    //     { "country_id": "BS", "name": "Bahamas" },
    //     { "country_id": "BH", "name": "Bahrain" },
    //     { "country_id": "BD", "name": "Bangladesh" },
    //     { "country_id": "BB", "name": "Barbados" },
    //     { "country_id": "BY", "name": "Belarus" },
    //     { "country_id": "BE", "name": "Belgium" },
    //     { "country_id": "BZ", "name": "Belize" },
    //     { "country_id": "BJ", "name": "Benin" },
    //     { "country_id": "BM", "name": "Bermuda" },
    //     { "country_id": "BT", "name": "Bhutan" },
    //     { "country_id": "BO", "name": "Bolivia" },
    //     { "country_id": "BA", "name": "Bosnia and Herzegovina" },
    //     { "country_id": "BW", "name": "Botswana" },
    //     { "country_id": "BV", "name": "Bouvet Island" },
    //     { "country_id": "BR", "name": "Brazil" },
    //     { "country_id": "IO", "name": "British Indian Ocean Territory" },
    //     { "country_id": "BN", "name": "Brunei Darussalam" },
    //     { "country_id": "BG", "name": "Bulgaria" },
    //     { "country_id": "BF", "name": "Burkina Faso" },
    //     { "country_id": "BI", "name": "Burundi" },
    //     { "country_id": "KH", "name": "Cambodia" },
    //     { "country_id": "CM", "name": "Cameroon" },
    //     { "country_id": "CA", "name": "Canada" },
    //     { "country_id": "CV", "name": "Cape Verde" },
    //     { "country_id": "KY", "name": "Cayman Islands" },
    //     { "country_id": "CF", "name": "Central African Republic" },
    //     { "country_id": "TD", "name": "Chad" },
    //     { "country_id": "CL", "name": "Chile" },
    //     { "country_id": "CN", "name": "China" },
    //     { "country_id": "CX", "name": "Christmas Island" },
    //     { "country_id": "CC", "name": "Cocos (Keeling) Islands" },
    //     { "country_id": "CO", "name": "Colombia" },
    //     { "country_id": "KM", "name": "Comoros" },
    //     { "country_id": "CG", "name": "Congo" },
    //     { "country_id": "CD", "name": "Congo, the Democratic Republic of the" },
    //     { "country_id": "CK", "name": "Cook Islands" },
    //     { "country_id": "CR", "name": "Costa Rica" },
    //     { "country_id": "CI", "name": "Cote d'Ivoire" },
    //     { "country_id": "HR", "name": "Croatia" },
    //     { "country_id": "CU", "name": "Cuba" },
    //     { "country_id": "CY", "name": "Cyprus" },
    //     { "country_id": "CZ", "name": "Czech Republic" },
    //     { "country_id": "DK", "name": "Denmark" },
    //     { "country_id": "DJ", "name": "Djibouti" },
    //     { "country_id": "DM", "name": "Dominica" },
    //     { "country_id": "DO", "name": "Dominican Republic" },
    //     { "country_id": "EC", "name": "Ecuador" },
    //     { "country_id": "EG", "name": "Egypt" },
    //     { "country_id": "SV", "name": "El Salvador" },
    //     { "country_id": "GQ", "name": "Equatorial Guinea" },
    //     { "country_id": "ER", "name": "Eritrea" },
    //     { "country_id": "EE", "name": "Estonia" },
    //     { "country_id": "ET", "name": "Ethiopia" },
    //     { "country_id": "FK", "name": "Falkland Islands (Malvinas)" },
    //     { "country_id": "FO", "name": "Faroe Islands" },
    //     { "country_id": "FJ", "name": "Fiji" },
    //     { "country_id": "FI", "name": "Finland" },
    //     { "country_id": "FR", "name": "France" },
    //     { "country_id": "GF", "name": "French Guiana" },
    //     { "country_id": "PF", "name": "French Polynesia" },
    //     { "country_id": "TF", "name": "French Southern Territories" },
    //     { "country_id": "GA", "name": "Gabon" },
    //     { "country_id": "GM", "name": "Gambia" },
    //     { "country_id": "GE", "name": "Georgia" },
    //     { "country_id": "DE", "name": "Germany" },
    //     { "country_id": "GH", "name": "Ghana" },
    //     { "country_id": "GI", "name": "Gibraltar" },
    //     { "country_id": "GR", "name": "Greece" },
    //     { "country_id": "GL", "name": "Greenland" },
    //     { "country_id": "GD", "name": "Grenada" },
    //     { "country_id": "GP", "name": "Guadeloupe" },
    //     { "country_id": "GU", "name": "Guam" },
    //     { "country_id": "GT", "name": "Guatemala" },
    //     { "country_id": "GG", "name": "Guernsey" },
    //     { "country_id": "GN", "name": "Guinea" },
    //     { "country_id": "GW", "name": "Guinea-Bissau" },
    //     { "country_id": "GY", "name": "Guyana" },
    //     { "country_id": "HT", "name": "Haiti" },
    //     { "country_id": "HM", "name": "Heard Island and McDonald Islands" },
    //     { "country_id": "VA", "name": "Holy See (Vatican City State)" },
    //     { "country_id": "HN", "name": "Honduras" },
    //     { "country_id": "HK", "name": "Hong Kong" },
    //     { "country_id": "HU", "name": "Hungary" },
    //     { "country_id": "IS", "name": "Iceland" },
    //     { "country_id": "IN", "name": "India" },
    //     { "country_id": "ID", "name": "Indonesia" },
    //     { "country_id": "IR", "name": "Iran, Islamic Republic of" },
    //     { "country_id": "IQ", "name": "Iraq" },
    //     { "country_id": "IE", "name": "Ireland" },
    //     { "country_id": "IM", "name": "Isle of Man" },
    //     { "country_id": "IL", "name": "Israel" },
    //     { "country_id": "IT", "name": "Italy" },
    //     { "country_id": "JM", "name": "Jamaica" },
    //     { "country_id": "JP", "name": "Japan" },
    //     { "country_id": "JE", "name": "Jersey" },
    //     { "country_id": "JO", "name": "Jordan" },
    //     { "country_id": "KZ", "name": "Kazakhstan" },
    //     { "country_id": "KE", "name": "Kenya" },
    //     { "country_id": "KI", "name": "Kiribati" },
    //     { "country_id": "KP", "name": "Korea, Democratic People's Republic of" },
    //     { "country_id": "KR", "name": "Korea, Republic of" },
    //     { "country_id": "KW", "name": "Kuwait" },
    //     { "country_id": "KG", "name": "Kyrgyzstan" },
    //     { "country_id": "LA", "name": "Lao People's Democratic Republic" },
    //     { "country_id": "LV", "name": "Latvia" },
    //     { "country_id": "LB", "name": "Lebanon" },
    //     { "country_id": "LS", "name": "Lesotho" },
    //     { "country_id": "LR", "name": "Liberia" },
    //     { "country_id": "LY", "name": "Libyan Arab Jamahiriya" },
    //     { "country_id": "LI", "name": "Liechtenstein" },
    //     { "country_id": "LT", "name": "Lithuania" },
    //     { "country_id": "LU", "name": "Luxembourg" },
    //     { "country_id": "MO", "name": "Macao" },
    //     { "country_id": "MK", "name": "Macedonia, the Former Yugoslav Republic of" },
    //     { "country_id": "MG", "name": "Madagascar" },
    //     { "country_id": "MW", "name": "Malawi" },
    //     { "country_id": "MY", "name": "Malaysia" },
    //     { "country_id": "MV", "name": "Maldives" },
    //     { "country_id": "ML", "name": "Mali" },
    //     { "country_id": "MT", "name": "Malta" },
    //     { "country_id": "MH", "name": "Marshall Islands" },
    //     { "country_id": "MQ", "name": "Martinique" },
    //     { "country_id": "MR", "name": "Mauritania" },
    //     { "country_id": "MU", "name": "Mauritius" },
    //     { "country_id": "YT", "name": "Mayotte" },
    //     { "country_id": "MX", "name": "Mexico" },
    //     { "country_id": "FM", "name": "Micronesia, Federated States of" },
    //     { "country_id": "MD", "name": "Moldova, Republic of" },
    //     { "country_id": "MC", "name": "Monaco" },
    //     { "country_id": "MN", "name": "Mongolia" },
    //     { "country_id": "ME", "name": "Montenegro" },
    //     { "country_id": "MS", "name": "Montserrat" },
    //     { "country_id": "MA", "name": "Morocco" },
    //     { "country_id": "MZ", "name": "Mozambique" },
    //     { "country_id": "MM", "name": "Myanmar" },
    //     { "country_id": "NA", "name": "Namibia" },
    //     { "country_id": "NR", "name": "Nauru" },
    //     { "country_id": "NP", "name": "Nepal" },
    //     { "country_id": "NL", "name": "Netherlands" },
    //     { "country_id": "AN", "name": "Netherlands Antilles" },
    //     { "country_id": "NC", "name": "New Caledonia" },
    //     { "country_id": "NZ", "name": "New Zealand" },
    //     { "country_id": "NI", "name": "Nicaragua" },
    //     { "country_id": "NE", "name": "Niger" },
    //     { "country_id": "NG", "name": "Nigeria" },
    //     { "country_id": "NU", "name": "Niue" },
    //     { "country_id": "NF", "name": "Norfolk Island" },
    //     { "country_id": "MP", "name": "Northern Mariana Islands" },
    //     { "country_id": "NO", "name": "Norway" },
    //     { "country_id": "OM", "name": "Oman" },
    //     { "country_id": "PK", "name": "Pakistan" },
    //     { "country_id": "PW", "name": "Palau" },
    //     { "country_id": "PS", "name": "Palestinian Territory, Occupied" },
    //     { "country_id": "PA", "name": "Panama" },
    //     { "country_id": "PG", "name": "Papua New Guinea" },
    //     { "country_id": "PY", "name": "Paraguay" },
    //     { "country_id": "PE", "name": "Peru" },
    //     { "country_id": "PH", "name": "Philippines" },
    //     { "country_id": "PN", "name": "Pitcairn" },
    //     { "country_id": "PL", "name": "Poland" },
    //     { "country_id": "PT", "name": "Portugal" },
    //     { "country_id": "PR", "name": "Puerto Rico" },
    //     { "country_id": "QA", "name": "Qatar" },
    //     { "country_id": "RE", "name": "Reunion" },
    //     { "country_id": "RO", "name": "Romania" },
    //     { "country_id": "RU", "name": "Russian Federation" },
    //     { "country_id": "RW", "name": "Rwanda" },
    //     { "country_id": "SH", "name": "Saint Helena" },
    //     { "country_id": "KN", "name": "Saint Kitts and Nevis" },
    //     { "country_id": "LC", "name": "Saint Lucia" },
    //     { "country_id": "PM", "name": "Saint Pierre and Miquelon" },
    //     { "country_id": "VC", "name": "Saint Vincent and the Grenadines" },
    //     { "country_id": "WS", "name": "Samoa" },
    //     { "country_id": "SM", "name": "San Marino" },
    //     { "country_id": "ST", "name": "Sao Tome and Principe" },
    //     { "country_id": "SA", "name": "Saudi Arabia" },
    //     { "country_id": "SN", "name": "Senegal" },
    //     { "country_id": "RS", "name": "Serbia" },
    //     { "country_id": "SC", "name": "Seychelles" },
    //     { "country_id": "SL", "name": "Sierra Leone" },
    //     { "country_id": "SG", "name": "Singapore" },
    //     { "country_id": "SK", "name": "Slovakia" },
    //     { "country_id": "SI", "name": "Slovenia" },
    //     { "country_id": "SB", "name": "Solomon Islands" },
    //     { "country_id": "SO", "name": "Somalia" },
    //     { "country_id": "ZA", "name": "South Africa" },
    //     { "country_id": "GS", "name": "South Georgia and the South Sandwich Islands" },
    //     { "country_id": "ES", "name": "Spain" },
    //     { "country_id": "LK", "name": "Sri Lanka" },
    //     { "country_id": "SD", "name": "Sudan" },
    //     { "country_id": "SR", "name": "Suriname" },
    //     { "country_id": "SJ", "name": "Svalbard and Jan Mayen" },
    //     { "country_id": "SZ", "name": "Swaziland" },
    //     { "country_id": "SE", "name": "Sweden" },
    //     { "country_id": "CH", "name": "Switzerland" },
    //     { "country_id": "SY", "name": "Syrian Arab Republic" },
    //     { "country_id": "TW", "name": "Taiwan, Province of China" },
    //     { "country_id": "TJ", "name": "Tajikistan" },
    //     { "country_id": "TZ", "name": "Tanzania, United Republic of" },
    //     { "country_id": "TH", "name": "Thailand" },
    //     { "country_id": "TL", "name": "Timor-Leste" },
    //     { "country_id": "TG", "name": "Togo" },
    //     { "country_id": "TK", "name": "Tokelau" },
    //     { "country_id": "TO", "name": "Tonga" },
    //     { "country_id": "TT", "name": "Trinidad and Tobago" },
    //     { "country_id": "TN", "name": "Tunisia" },
    //     { "country_id": "TR", "name": "Turkey" },
    //     { "country_id": "TM", "name": "Turkmenistan" },
    //     { "country_id": "TC", "name": "Turks and Caicos Islands" },
    //     { "country_id": "TV", "name": "Tuvalu" },
    //     { "country_id": "UG", "name": "Uganda" },
    //     { "country_id": "UA", "name": "Ukraine" },
    //     { "country_id": "AE", "name": "United Arab Emirates" },
    //     { "country_id": "GB", "name": "United Kingdom" },
    //     { "country_id": "US", "name": "United States" },
    //     { "country_id": "UM", "name": "United States Minor Outlying Islands" },
    //     { "country_id": "UY", "name": "Uruguay" },
    //     { "country_id": "UZ", "name": "Uzbekistan" },
    //     { "country_id": "VU", "name": "Vanuatu" },
    //     { "country_id": "VE", "name": "Venezuela" },
    //     { "country_id": "VN", "name": "Viet Nam" },
    //     { "country_id": "VG", "name": "Virgin Islands, British" },
    //     { "country_id": "VI", "name": "Virgin Islands, U.S." },
    //     { "country_id": "WF", "name": "Wallis and Futuna" },
    //     { "country_id": "EH", "name": "Western Sahara" },
    //     { "country_id": "YE", "name": "Yemen" },
    //     { "country_id": "ZM", "name": "Zambia" },
    //     { "country_id": "ZW", "name": "Zimbabwe" }
    //   ];

    public stateList:any=[
        {
            id:1,
            states:[
                { "state_id": 1, "state_name": "Andaman and Nicobar Islands" },
                { "state_id": 2, "state_name": "Andhra Pradesh" },
                { "state_id": 3, "state_name": "Arunachal Pradesh" },
                { "state_id": 4, "state_name": "Assam" },
                { "state_id": 5, "state_name": "Bihar" },
                { "state_id": 6, "state_name": "Chandigarh" },
                { "state_id": 7, "state_name": "Chhattisgarh" },
                { "state_id": 8, "state_name": "Dadra and Nagar Haveli" },
                { "state_id": 9, "state_name": "Daman and Diu" },
                { "state_id": 10, "state_name": "Delhi" },
                { "state_id": 11, "state_name": "Goa" },
                { "state_id": 12, "state_name": "Gujarat" },
                { "state_id": 13, "state_name": "Haryana" },
                { "state_id": 14, "state_name": "Himachal Pradesh" },
                { "state_id": 15, "state_name": "Jammu and Kashmir" },
                { "state_id": 16, "state_name": "Jharkhand" },
                { "state_id": 17, "state_name": "Karnataka" },
                { "state_id": 18, "state_name": "Kerala" },
                { "state_id": 19, "state_name": "Ladakh" },
                { "state_id": 20, "state_name": "Lakshadweep" },
                { "state_id": 21, "state_name": "Madhya Pradesh" },
                { "state_id": 22, "state_name": "Maharashtra" },
                { "state_id": 23, "state_name": "Manipur" },
                { "state_id": 24, "state_name": "Meghalaya" },
                { "state_id": 25, "state_name": "Mizoram" },
                { "state_id": 26, "state_name": "Nagaland" },
                { "state_id": 27, "state_name": "Odisha" },
                { "state_id": 28, "state_name": "Puducherry" },
                { "state_id": 29, "state_name": "Punjab" },
                { "state_id": 30, "state_name": "Rajasthan" },
                { "state_id": 31, "state_name": "Sikkim" },
                { "state_id": 32, "state_name": "Tamil Nadu" },
                { "state_id": 33, "state_name": "Telangana" },
                { "state_id": 34, "state_name": "Tripura" },
                { "state_id": 35, "state_name": "Uttar Pradesh" },
                { "state_id": 36, "state_name": "Uttarakhand" },
                { "state_id": 37, "state_name": "West Bengal" }
              ]
              
        },
        {
            id:2,
            states:[
                { "state_id": 1, "state_name": "Alabama" },
                { "state_id": 2, "state_name": "Alaska" },
                { "state_id": 3, "state_name": "Arizona" },
                { "state_id": 4, "state_name": "Arkansas" },
                { "state_id": 5, "state_name": "California" },
                { "state_id": 6, "state_name": "Colorado" },
                { "state_id": 7, "state_name": "Connecticut" },
                { "state_id": 8, "state_name": "Delaware" },
                { "state_id": 9, "state_name": "District of Columbia" },
                { "state_id": 10, "state_name": "Florida" },
                { "state_id": 11, "state_name": "Georgia" },
                { "state_id": 12, "state_name": "Hawaii" },
                { "state_id": 13, "state_name": "Idaho" },
                { "state_id": 14, "state_name": "Illinois" },
                { "state_id": 15, "state_name": "Indiana" },
                { "state_id": 16, "state_name": "Iowa" },
                { "state_id": 17, "state_name": "Kansas" },
                { "state_id": 18, "state_name": "Kentucky" },
                { "state_id": 19, "state_name": "Louisiana" },
                { "state_id": 20, "state_name": "Maine" },
                { "state_id": 21, "state_name": "Maryland" },
                { "state_id": 22, "state_name": "Massachusetts" },
                { "state_id": 23, "state_name": "Michigan" },
                { "state_id": 24, "state_name": "Minnesota" },
                { "state_id": 25, "state_name": "Mississippi" },
                { "state_id": 26, "state_name": "Missouri" },
                { "state_id": 27, "state_name": "Montana" },
                { "state_id": 28, "state_name": "Nebraska" },
                { "state_id": 29, "state_name": "Nevada" },
                { "state_id": 30, "state_name": "New Hampshire" },
                { "state_id": 31, "state_name": "New Jersey" },
                { "state_id": 32, "state_name": "New Mexico" },
                { "state_id": 33, "state_name": "New York" },
                { "state_id": 34, "state_name": "North Carolina" },
                { "state_id": 35, "state_name": "North Dakota" },
                { "state_id": 36, "state_name": "Ohio" },
                { "state_id": 37, "state_name": "Oklahoma" },
                { "state_id": 38, "state_name": "Oregon" },
                { "state_id": 39, "state_name": "Pennsylvania" },
                { "state_id": 40, "state_name": "Rhode Island" },
                { "state_id": 41, "state_name": "South Carolina" },
                { "state_id": 42, "state_name": "South Dakota" },
                { "state_id": 43, "state_name": "Tennessee" },
                { "state_id": 44, "state_name": "Texas" },
                { "state_id": 45, "state_name": "Utah" },
                { "state_id": 46, "state_name": "Vermont" },
                { "state_id": 47, "state_name": "Virginia" },
                { "state_id": 48, "state_name": "Washington" },
                { "state_id": 49, "state_name": "West Virginia" },
                { "state_id": 50, "state_name": "Wisconsin" },
                { "state_id": 51, "state_name": "Wyoming" }
              ]
        }
    ]  ;
    
    public cityList:any=[
        {
            country_id:1,
            state_id:35,
            cityList:[
                {
                    id:1,
                    name:'Raebareli'
                },
                {
                    id:2,
                    name:'Lucknow'
                },
                {
                    id:3,
                    name:'Kanpur'
                },
                {
                    id:4,
                    name:'Noida'
                },
            ]
        },
        {
            country_id:2,
            state_id:5,
            cityList:[
                    {
                        id:1,
                        name:'Los Angeles'
                    },
                    {
                        id:2,
                        name:'San Francisco'
                    },
                    {
                        id:3,
                        name:'San Diego'
                    },
                    {
                        id:4,
                        name:'San Jose'
                    },
            ]
        }
    ]
      



}